name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /var/www/herramientas-rv/herramientas-rv
          git pull origin main
          cd backend
          npm install
          npm run build
          pm2 restart all
          cd ../frontend
          npm install
          npm run build
          # Aquí puedes agregar comandos para mover los archivos de construcción a tu servidor web, si es necesario
        EOF
